version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
